"""empty message

Revision ID: 885d45f6f3e9
Revises: b2059b30e60e
Create Date: 2021-06-13 19:16:50.993343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '885d45f6f3e9'
down_revision = 'b2059b30e60e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('authorization_role',
    sa.Column('authorization_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['authorization_id'], ['authorization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.add_column('user', sa.Column('name', sa.UnicodeText(), nullable=True))
    op.add_column('user', sa.Column('totp_secret', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_role', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_role', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_user_role_role_end', table_name='user_role')
    op.drop_index('ix_user_role_role_id', table_name='user_role')
    op.drop_index('ix_user_role_role_start', table_name='user_role')
    op.drop_index('ix_user_role_user_id', table_name='user_role')
    op.drop_column('user_role', 'role_end')
    op.drop_column('user_role', 'role_start')
    op.drop_column('user_role', 'created_at')
    op.drop_column('user_role', 'id')
    op.drop_column('user_role', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user_role', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('user_role', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user_role', sa.Column('role_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_role', sa.Column('role_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_user_role_user_id', 'user_role', ['user_id'], unique=False)
    op.create_index('ix_user_role_role_start', 'user_role', ['role_start'], unique=False)
    op.create_index('ix_user_role_role_id', 'user_role', ['role_id'], unique=False)
    op.create_index('ix_user_role_role_end', 'user_role', ['role_end'], unique=False)
    op.alter_column('user_role', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_role', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'totp_secret')
    op.drop_column('user', 'name')
    op.drop_table('authorization_role')
    op.drop_table('authorization')
    # ### end Alembic commands ###
